"""soaps table again

Revision ID: 1bd928c4a8cf
Revises: 248408b4768f
Create Date: 2023-08-19 14:02:00.621669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd928c4a8cf'
down_revision = '248408b4768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_soaps_patient_id_patients'), 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_soaps_vet_id_vets'), 'vets', ['vet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_soaps_vet_id_vets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_soaps_patient_id_patients'), type_='foreignkey')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('vet_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
