"""soap table

Revision ID: 248408b4768f
Revises: dc8829a52d34
Create Date: 2023-08-17 21:55:29.744668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248408b4768f'
down_revision = 'dc8829a52d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ailment', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soaps')
    # ### end Alembic commands ###
